<?php

namespace Tests\Feature;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use App\Post;

class ViewPostTest extends TestCase
{
    protected $post;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->post = factory('App\Post')->create();
    }

    public function testUserCanViewAllBlogPosts()
    {
        $this->get('/posts')->assertSee($this->post->title);
    }

    public function testUserCanViewSingleBlogPost()
    {
        $this->get('/posts/' . $this->post->id)->assertSee($this->post->title);
    }

     public function testUserCanViewCommetsAssociatedWithPost()
    {
        $comment = factory('App\Comment')->create([ 'post_id' => $this->post->id]);
        $this->get('/posts/' . $this->post->id)->assertSee($comment->text);
    }

}
